### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by westor7** [mIRC-Scripters/mSL-VSCode-Extension#16]
What is the name of Theme you use for Visual Studio Code in https://raw.githubusercontent.com/mIRC-Scripters/mSL-VSCode-Extension/master/preview.gif ?

I am trying to find it but i can't :P

**Comment by Kedyn** [comment]
No idea, I no longer have that theme. I used to look for themes here: https://vscodethemes.com/dark?page=1 . I cannot seem to find it. So, I must of edit a theme to get those colors because at some point I used to play around with the themes.

**Comment by westor7** [comment]
Just trying to find one that is going to work great with mSL.

E.g: $identifiers %variables etc...

**Comment by Kedyn** [comment]
Questions should go in the discussion section of the repository, to keep the issues for enhancements and issues. closing this issue
