### ISSUE TITLE
Parse old, but valid syntax? E.g.: echo -a $dir='select dir' c:\

### ISSUE THREAD

**Issue by acvxqs** [mIRC-Scripters/mSL-VSCode-Extension#2]
Talking about `$dir` and `$hfile`:

https://en.wikichip.org/wiki/mirc/identifiers/$dir
https://en.wikichip.org/wiki/mirc/identifiers/$hfile

Note: I havent included them for the moment...

**Comment by Kedyn** [comment]
This goes back to, whether or not to add deprecated identifiers/commands. I do think giving support to old scripts is a good thing. So we should add those, but they should have a lower priority.

**Comment by Kedyn** [comment]
Both of these have been added
