### ISSUE TITLE
Add support for adiirc? (https://adiirc.com)

### ISSUE THREAD

**Issue by acvxqs** [mIRC-Scripters/mSL-VSCode-Extension#3]
It's another IRC client, but comes with built-in mSL.. Some identifiers/commands aren't in mIRC and some mIRC identifiers/commands aren't in adiirc.

Should we add support for adiirc?

I think it would be some extra work, but worth it.

**Comment by Kedyn** [comment]
Sounds good to me. Do adiirc files utilize the same extension, or would we have to add another one?

**Comment by acvxqs** [comment]
I've asked and kr0n answered that it can read from .ini as well as .mrc or any file extension really. There's no 'default'.

**Comment by acvxqs** [comment]
Commands: https://dev.adiirc.com/projects/adiirc/wiki/Scripting_Commands
Identifiers: https://dev.adiirc.com/projects/adiirc/wiki/Scripting_Identifiers

**Comment by acvxqs** [comment]
@Kedyn I've added 'C' identifiers for adiirc now, but left $calcint() out. It looks like we want to add it to the regex used for $calc...just touching base with you on this one. (https://dev.adiirc.com/projects/adiirc/wiki/$calcint)

**Comment by acvxqs** [comment]
@Kedyn I'm tackling the identifiers & commands. Seems there's also adiirc specific 'events'. Link: https://dev.adiirc.com/projects/adiirc/wiki/Scripting_Events

**Comment by acvxqs** [comment]
Completed in 9c4b318
