### ISSUE TITLE
Not sure how to match the $parmN identifier.

### ISSUE THREAD

**Issue by acvxqs** [mIRC-Scripters/mSL-VSCode-Extension#6]
If I add `|parm\d+|` it errors in the console...

**Comment by Kedyn** [comment]
Because we are working with strings and not regex, we must escape `"\"`. Therefore, something like `"\d"` would become `"\\d:"`

**Comment by acvxqs** [comment]
Closed in 56f980ddac20afa4ef46ee034ec85760272afb4a
