### ISSUE TITLE
New logo(s) ...

### ISSUE THREAD

**Issue by acvxqs** [mIRC-Scripters/mSL-VSCode-Extension#8]
We're looking for new logo(s)...

I've taken the liberty to spend some time wrestling with the GIMP to create the following:

![BLUE_CUBE_MSL](https://user-images.githubusercontent.com/13683523/73938275-33af6780-48e7-11ea-9216-984bd579035b.png)

I've set it as an avatar pic for the 'mIRC Scripters' org, replacing the default one.
edit: not definitive, merely a suggestion and see-how-it-looks-check.

Maybe create a new repository where we could publish all (our) creative GIMP/Inkscape/Photoshop ideas to and set a license?

**Comment by acvxqs** [comment]
![mIRC_black_on_white](https://user-images.githubusercontent.com/13683523/73961122-4b4d1700-490c-11ea-8b7f-76ffa8faa4c0.png)

**Comment by Kedyn** [comment]
![logo](https://user-images.githubusercontent.com/11042906/74216983-ed496800-4c5a-11ea-84de-d726cdf9f08d.png)

**Comment by acvxqs** [comment]
The second one 'mIRC' doesn't cut it. It's about adiirc as well. So the 'mSL' message is much better! I'm voting for yours @Kedyn !

**Comment by acvxqs** [comment]
gms from irc.mircscripts.net fame has been working on logo's as well. He wanted to share these. (svg available upon request).

https://imgur.com/a/PSg3sZO

**Comment by Kedyn** [comment]
Awesome stuff, but as we previously mention on IRC we might want to not only show mIRC because we now also support AdiIRC.
